# Generated by Django 3.0.5 on 2020-04-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200426_2128'),
        ('users', '0002_auto_20200426_1931'),
    ]

    operations = [
    ]
