FIT = 0
ISE = 1
BS = 2
KMA = 3
MCM = 4
CHEM = 5
GEO = 6
OIL = 7
FACULTIES = (
    (FIT, 'FACULTY OF INFORMATION TECHNOLOGIES'),
    (ISE, 'INTERNATIONAL SCHOOL OF ECONOMICS'),
    (BS, 'BUSINESS SCHOOL'),
    (KMA, 'KAZAKHSTAN MARITIME ACADEMY'),
    (MCM, 'SCHOOL OF MATHEMATICS AND CYBERNETICS'),
    (CHEM, 'SCHOOL OF CHEMICAL ENGINEERING'),
    (GEO, 'FACULTY OF GEOLOGY AND EXPLORATION'),
    (OIL, 'FACULTY OF ENERGY AND OIL ANG GAS INDUSTRY')
)